# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with MVN


    
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    defaults:
     run:
      working-directory: .
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
#           - nickname: win
#             os: windows-latest
#             graal: 22.3.0
#             musl: false
#           - nickname: macos
#             os: macos-latest
#             graal: 22.3.0
#             musl: false
          - nickname: linux
            os: ubuntu-latest
            graal: 22.3.0
            musl: true
            java: 17

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository/*/*
            !~/.m2/repository/com/arakoo
          key: ${{ runner.os }}-cron-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-cron-maven
            ${{ runner.os }}-maven

      - name: Install JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Build  - JVM
        run: mvn clean package   

      - name: Move App Bundle to location
        run: cp target/flyfly-0.0.1-SNAPSHOT.jar ./flyfly.jar
      - uses: actions/upload-artifact@v3
        with:
          name: flyfly-artifact-rel
          path: |
            ./project/flyfly/flyfly.jar
            ./project/flyfly/pom.xml
        
      - name: Publish test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
         name: test-results
         path: build/reports/tests/
    outputs:
      relid: ${{ steps.versioninfo.outputs.pipeline_id }}
